name: CI/CD to test, build, and deploy  
on:
  push:
    branches:
      - dev
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    # Selecting node js
    - uses: actions/setup-node@v3
      with:
        node-version: "20.x"
        cache: 'npm'

    # Building packages   
    - run: npm i
    - run: npm test
    - run: npm run deploy
